### ISSUE TITLE
Data lost when saving structured field in another language

### ISSUE THREAD

**Issue by hdodov** [medienbaecker/kirby-fieldtoggle#11]
The plugin works perfectly in my main language (Bulgarian). However, when I switch to English, translate a field, and click save - only the translated field is saved. The rest are set to `NULL`. Here’s my blueprint:

```
title:
  en: Contacts
  bg: Контакти
icon: phone

pages: false

files: false

fields:
  title:
    label:
      en: Title
      bg: Заглавие
    type: text
  links:
    label:
      en: Links
      bg: Връзки
    type: structure
    fields:
      type:
        label:
          en: Type
          bg: Тип връзка
        type: fieldtoggle
        options:
          facebook:
            en: Facebook page
            bg: Фейсбук страница
          email:
            en: Email address
            bg: Имейл адрес
          telephone:
            en: Telephone number
            bg: Телефонен номер
        show:
          facebook: link
          email: email
          telephone: telephone
        hide:
          facebook: email telephone
          email: link telephone
          telephone: link email
        translate: false
      name:
        label:
          en: Name
          bg: Име
        type: text
      link:
        label:
          en: Address
          bg: Адрес
        type: url
        translate: false
      telephone:
        label:
          en: Number
          bg: Номер
        type: tel
        translate: false
      email:
        label:
          en: Address
          bg: Адрес
        type: email
        translate: false
```

Let’s say I go to the panel, select `email` for `type`, type `Тест` for `name`, fill in the `email` field, and click Save. Data is saved, everything is fine. Then, when I select EN for the language and click on the entry I just created, I can only modify `name`, which should happen. However, when I modify it and click Save, all data but `name` is lost.

`contacts.bg.txt` and `contacts.en.txt` before saving:
```
- 
  type: email
  name: Тест
  link: ""
  telephone: ""
  email: example@gmail.com
```

`contacts.en.txt` after saving:
```
- 
  type: null
  name: Test
  link: null
  telephone: null
  email: null
```
