### ISSUE TITLE
Also allow fieldtoggle for select fields

### ISSUE THREAD

**Issue by ldanielswakman** [medienbaecker/kirby-fieldtoggle#3]
This would allow for more complex data entry; it could work in a similar way that `on: text` and `off: info` works for switching field visibility, but instead you specify which fields should be visible for each select option. E.g.:
```
category:
  label: Category
  type: selecttoggle
  default: design
  design: sub_discipline description
  architecture: school
  photography: fav_camera
  options:
    design: Design
    architecture: Architecture
    photography: Photography
```

**Comment by medienbaecker** [comment]
That's a nice addition and would allow way more complex scenarios. We would probably have to create another field for that, though.

**Comment by ldanielswakman** [comment]
You're right, sounds like a great idea to have a separate plugin for that :), `kirby-selecttoggle` for instance. Logic should be exactly the same as you built for this field type though, right?

**Comment by medienbaecker** [comment]
Yes, it is probably ~90% the same. But I think the field will have to extend the default select field, instead of the default toggle field. **Maybe** there's a way to change this in the blueprint with a value like `select: true`. I'm going to have a look.

**Comment by medienbaecker** [comment]
It's not as easy as it seemed, unfortunately. [In this line](https://github.com/medienbaecker/kirby-fieldtoggle/blob/master/fieldtoggle/fieldtoggle.php#L19-L24) the options like `on` or `off` have to be set. If the options are user defined, this is not possible.

Maybe the blueprint will look something like that:

```
category:
  label: Category
  type: selecttoggle
  default: design
  options:
    Design: sub_discipline description
    Architecture: school
    Photography: fav_camera
```

This will make it harder to use the select values in the template, though.

**Comment by ldanielswakman** [comment]
Hm pity; can't you use the 'slug' versions of the objects like `design`? Why did you flip the slug and the title in your example?

**Comment by medienbaecker** [comment]
I didn't flip the slug and title. The second parameter are the fields that will be toggled.

**Comment by ldanielswakman** [comment]
Hm I guess I'm not caught up into the code (and Kirby plugins) as much as you are; just that the [select field](https://getkirby.com/docs/cheatsheet/panel-fields/select) saves the slug, which is the first part of the options. 
So yeah you might need a different function for on/off select or multiple options select, but in that function it could be something like `if (isset($this->design)) { $item->data('design',$this->design); }`, where you would need to create a loop over the select options. Does that make any sense?

**Comment by medienbaecker** [comment]
After thinking long and hard about this, I'm trying to make the following work right now:

```
category:
    label: Category
    type:  fieldtoggle
    options:
        design: Design
        architecture: Architecture
        photography: Photography
    toggles:
        design: sub_discipline description
        architecture: school
        photography: fav_camera
```

This makes it possible to have both a "uid", a "label" and the toggling feature for every select option or radio button.

**Comment by ldanielswakman** [comment]
Ooh that looks interesting for sure! And this could/would work with a simple on/of toggle as well? For instance when you don't define `options` in the fieldtoggle, it will switch to on/off (with single level depth), and when you do define options it switches to the option-based toggling?

**Comment by medienbaecker** [comment]
A simple on/off toggle would then look like this:

category:
```
    label: Toggle
    type:  fieldtoggle
    options:
        yes: Yes
        no: No
    on:
        yes: some_field
        no: another_field
```

You won't need the `off` in for most cases. Only if fields should become visible when the state of this option is **not** active.
