### ISSUE TITLE
Add Default Option

### ISSUE THREAD

**Issue by calebgrove** [medienbaecker/kirby-fieldtoggle#6]
It would be really handy if I could define the default selected option for this field. For example:

~~~~ yaml
imagetoggle:
  label: Show image?
  type: fieldtoggle
  default: no
  options:
    yes: "Yes"
    no: "No"
  show:
    yes: imagefield
  hide:
    no: imagefield
imagefield:
  label: Image
  type: image
~~~~

**Comment by medienbaecker** [comment]
The default option should actually work just like that. I will try to reproduce this, give me a second...

**Comment by medienbaecker** [comment]
Ok, I think I found out why this happens. Yes and no seem to be similar to "true" and "false" in YAML. 
Simply use `"` around them like that:

```
imagetoggle:
  label: Show image?
  type: fieldtoggle
  default: "no"
  options:
    yes: "Yes"
    no: "No"
  show:
    yes: imagefield
  hide:
    no: imagefield
imagefield:
  label: Image
  type: image
```
